In [38]:
from math import sqrt
import numpy as np
import pandas as pd

In [2]:
def divisorGenerator(n):
    large_divisors = []
    for i in range(1, int(sqrt(n) + 1)):
        if n % i == 0:
            yield i
            if i*i != n:
                large_divisors.append(n / i)
    for divisor in reversed(large_divisors):
        yield divisor

In [3]:
I = [4e6, 8e6, 10e6, 16e6, 20e6, 24e6, 25e6]
M = range(2, 64)
N = range(50, 433)
P = [2, 4, 6, 8]


def relation(i, m, n, p):
    return (i * (1 / m) * n * (1 / p)) / 120

counter = 0
condidates = []
for i in I:
    for m in M:
        for n in N:
            for p in P:
                if counter % 1000 == 0:
                    print(counter)
                buff = relation(i, m, n, p)
                if buff >= 1200000:
                    continue
                if (round(buff) == buff) & (buff % 500 == 0):
                    condidates.append([buff, [i, m, n, p], list(divisorGenerator(int(buff)))])

                counter += 1

print(f"Number of Condidate : {len(condidates)}")

0
1000
1000
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
1560

In [4]:
new_condidates = []
for condidate in condidates:
    x = condidate[0]
    imnp = condidate[1]
    divisors = condidate[2]

    buff = []
    for divisor in divisors:
        if divisor % 500 == 0:
            buff.append(divisor // 500)

    if len(buff[1:]) >= 10:
        new_condidates.append([x, imnp, buff[1:]])

print(f"Number of New Condidate : {len(new_condidates)}")

Number of New Condidate : 17139


In [5]:
max_x = 0
for condidate in new_condidates:
    if max_x < condidate[0]:
        max_x = condidate[0]
        max_condidate = condidate

max_x

1196000.0

In [6]:
max_condidate

[1196000.0,
 [24000000.0, 25, 299, 2],
 [2,
  4.0,
  8.0,
  13.0,
  23.0,
  26.0,
  46.0,
  52.0,
  92.0,
  104.0,
  184.0,
  299.0,
  598.0,
  1196.0,
  2392.0]]

In [7]:
def co_prime(divisors):
    divisors.reverse()
    output_list = []
    counter = 1
    for divisor in divisors:
        buff = [divisor]
        for sub_divisor in divisors[counter:]:
            if divisor % sub_divisor != 0:
                buff.append(sub_divisor)     
        if len(buff) >= 10:
            output_list.append(buff) 
        counter += 1
    

    return output_list

In [8]:
def pop_notcoprime(divisors):
    buff = []
    for counter1 in range(len(divisors)):
        flag = 0
        for counter2 in range(len(divisors)):
            a = divisors[counter1]
            b = divisors[counter2]
            if a < b:
                a, b = b, a
            if a % b == 0:
                flag += 1
        buff.append(flag)
    if max(buff) == 1:
        return divisors
    else:
        divisors.pop(np.argmax(buff))
        return divisors

In [9]:
final_condidate = []
for counter, condidate in enumerate(new_condidates):
    if counter % 100 == 0:
        print(f"Counter : {counter}")
    x = condidate[0]
    imnp = condidate[1]
    divisors = condidate[2]
    
    
    all_co_primes = co_prime(divisors.copy())
    new_all_co_primes = []
    for all_co_prime in all_co_primes:
        len_co_prime = len(all_co_prime)
        
        while True:
            all_co_prime = pop_notcoprime(all_co_prime)
            if len_co_prime == len(all_co_prime):
                break
            else:
                len_co_prime = len(all_co_prime)
        
        if len(all_co_prime) >= 10:
            new_all_co_primes.append(all_co_prime)
    
    if len(new_all_co_primes) != 0:
        final_condidate.append([x, imnp, new_all_co_primes])

Counter : 0
Counter : 100
Counter : 200
Counter : 300
Counter : 400
Counter : 500
Counter : 600
Counter : 700
Counter : 800
Counter : 900
Counter : 1000
Counter : 1100
Counter : 1200
Counter : 1300
Counter : 1400
Counter : 1500
Counter : 1600
Counter : 1700
Counter : 1800
Counter : 1900
Counter : 2000
Counter : 2100
Counter : 2200
Counter : 2300
Counter : 2400
Counter : 2500
Counter : 2600
Counter : 2700
Counter : 2800
Counter : 2900
Counter : 3000
Counter : 3100
Counter : 3200
Counter : 3300
Counter : 3400
Counter : 3500
Counter : 3600
Counter : 3700
Counter : 3800
Counter : 3900
Counter : 4000
Counter : 4100
Counter : 4200
Counter : 4300
Counter : 4400
Counter : 4500
Counter : 4600
Counter : 4700
Counter : 4800
Counter : 4900
Counter : 5000
Counter : 5100
Counter : 5200
Counter : 5300
Counter : 5400
Counter : 5500
Counter : 5600
Counter : 5700
Counter : 5800
Counter : 5900
Counter : 6000
Counter : 6100
Counter : 6200
Counter : 6300
Counter : 6400
Counter : 6500
Counter : 6600
Counter

In [10]:
len(final_condidate)

71

In [11]:
final_condidate

[[630000.0,
  [4000000.0, 5, 189, 2],
  [[105.0, 70.0, 63.0, 45.0, 42.0, 30.0, 28.0, 20.0, 18.0, 12.0]]],
 [990000.0,
  [4000000.0, 5, 297, 2],
  [[165.0, 110.0, 99.0, 66.0, 45.0, 44.0, 30.0, 20.0, 18.0, 12.0]]],
 [1170000.0,
  [4000000.0, 5, 351, 2],
  [[195.0, 130.0, 117.0, 78.0, 52.0, 45.0, 30.0, 20.0, 18.0, 12.0]]],
 [630000.0,
  [4000000.0, 5, 378, 4],
  [[105.0, 70.0, 63.0, 45.0, 42.0, 30.0, 28.0, 20.0, 18.0, 12.0]]],
 [630000.0,
  [4000000.0, 10, 378, 2],
  [[105.0, 70.0, 63.0, 45.0, 42.0, 30.0, 28.0, 20.0, 18.0, 12.0]]],
 [630000.0,
  [8000000.0, 5, 189, 4],
  [[105.0, 70.0, 63.0, 45.0, 42.0, 30.0, 28.0, 20.0, 18.0, 12.0]]],
 [990000.0,
  [8000000.0, 5, 297, 4],
  [[165.0, 110.0, 99.0, 66.0, 45.0, 44.0, 30.0, 20.0, 18.0, 12.0]]],
 [1170000.0,
  [8000000.0, 5, 351, 4],
  [[195.0, 130.0, 117.0, 78.0, 52.0, 45.0, 30.0, 20.0, 18.0, 12.0]]],
 [630000.0,
  [8000000.0, 5, 378, 8],
  [[105.0, 70.0, 63.0, 45.0, 42.0, 30.0, 28.0, 20.0, 18.0, 12.0]]],
 [630000.0,
  [8000000.0, 10, 189, 2]

In [12]:
diff_var = []
set_x = []
max_x = 0
for condidate in final_condidate:
    if max_x < condidate[0]:
        max_x = condidate[0]
        max_condidate = condidate
    set_x.append(condidate[0])
    diff_var.append((condidate[2][0][0] - condidate[2][0][-1]) * 500) 

max_x

1170000.0

In [13]:
set(set_x)

{630000.0, 990000.0, 1155000.0, 1170000.0}

In [14]:
diff_var

[46500.0,
 76500.0,
 91500.0,
 46500.0,
 46500.0,
 46500.0,
 76500.0,
 91500.0,
 46500.0,
 46500.0,
 76500.0,
 91500.0,
 46500.0,
 46500.0,
 46500.0,
 46500.0,
 76500.0,
 91500.0,
 46500.0,
 76500.0,
 91500.0,
 46500.0,
 46500.0,
 76500.0,
 91500.0,
 46500.0,
 46500.0,
 46500.0,
 76500.0,
 91500.0,
 46500.0,
 46500.0,
 46500.0,
 76500.0,
 91500.0,
 46500.0,
 76500.0,
 35500.0,
 91500.0,
 46500.0,
 76500.0,
 91500.0,
 46500.0,
 46500.0,
 76500.0,
 35500.0,
 91500.0,
 46500.0,
 76500.0,
 91500.0,
 76500.0,
 46500.0,
 76500.0,
 91500.0,
 46500.0,
 46500.0,
 76500.0,
 35500.0,
 91500.0,
 46500.0,
 46500.0,
 76500.0,
 46500.0,
 46500.0,
 76500.0,
 91500.0,
 46500.0,
 46500.0,
 76500.0,
 46500.0,
 46500.0]

In [15]:
np.argmin(diff_var)

37

In [16]:
final_condidate[37]

[1155000.0,
 [24000000.0, 5, 231, 8],
 [[77.0, 55.0, 35.0, 33.0, 22.0, 21.0, 15.0, 14.0, 10.0, 6.0]]]

In [17]:
np.where(np.array(diff_var) == 35500)

(array([37, 45, 57]),)

In [18]:
final_condidate[37]

[1155000.0,
 [24000000.0, 5, 231, 8],
 [[77.0, 55.0, 35.0, 33.0, 22.0, 21.0, 15.0, 14.0, 10.0, 6.0]]]

In [19]:
final_condidate[45]

[1155000.0,
 [24000000.0, 10, 231, 4],
 [[77.0, 55.0, 35.0, 33.0, 22.0, 21.0, 15.0, 14.0, 10.0, 6.0]]]

In [20]:
final_condidate[57]

[1155000.0,
 [24000000.0, 20, 231, 2],
 [[77.0, 55.0, 35.0, 33.0, 22.0, 21.0, 15.0, 14.0, 10.0, 6.0]]]

In [21]:
set(diff_var)

{35500.0, 46500.0, 76500.0, 91500.0}

In [22]:
np.where(np.array(diff_var) == 46500)

(array([ 0,  3,  4,  5,  8,  9, 12, 13, 14, 15, 18, 21, 22, 25, 26, 27, 30,
        31, 32, 35, 39, 42, 43, 47, 51, 54, 55, 59, 60, 62, 63, 66, 67, 69,
        70]),)

In [23]:
len(np.where(np.array(diff_var) == 46500)[0])

35

In [24]:
max_x = 0
for index in np.where(np.array(diff_var) == 46500)[0]:
    if max_x < final_condidate[index][0]:
        max_x = final_condidate[index][0]

In [25]:
max_x

630000.0

In [26]:
np.where(np.array(diff_var) == 76500)

(array([ 1,  6, 10, 16, 19, 23, 28, 33, 36, 40, 44, 48, 50, 52, 56, 61, 64,
        68]),)

In [27]:
len(np.where(np.array(diff_var) == 76500)[0])

18

In [28]:
max_x = 0
for index in np.where(np.array(diff_var) == 76500)[0]:
    if max_x < final_condidate[index][0]:
        max_x = final_condidate[index][0]

In [29]:
max_x

990000.0

In [30]:
np.where(np.array(diff_var) == 91500)

(array([ 2,  7, 11, 17, 20, 24, 29, 34, 38, 41, 46, 49, 53, 58, 65]),)

In [31]:
len(np.where(np.array(diff_var) == 91500)[0])

15

In [32]:
max_x = 0
for index in np.where(np.array(diff_var) == 91500)[0]:
    if max_x < final_condidate[index][0]:
        max_x = final_condidate[index][0]

In [33]:
max_x

1170000.0

In [34]:
final_condidate[4]

[630000.0,
 [4000000.0, 10, 378, 2],
 [[105.0, 70.0, 63.0, 45.0, 42.0, 30.0, 28.0, 20.0, 18.0, 12.0]]]

In [40]:
BUFF = []
for condidate in final_condidate:
    buff = [condidate[0]] + condidate[1] + (np.array(condidate[2][0]) * 500).tolist()
    BUFF.append(buff)

In [47]:
df = pd.DataFrame(np.array(BUFF), columns=["X", "I", "M", "N", "P", "F10", "F9", "F8", "F7", "F6", "F5", "F4", "F3", "F2", "F1"])
df

X           I     M      N    P      F10       F9       F8  \
0    630000.0   4000000.0   5.0  189.0  2.0  52500.0  35000.0  31500.0   
1    990000.0   4000000.0   5.0  297.0  2.0  82500.0  55000.0  49500.0   
2   1170000.0   4000000.0   5.0  351.0  2.0  97500.0  65000.0  58500.0   
3    630000.0   4000000.0   5.0  378.0  4.0  52500.0  35000.0  31500.0   
4    630000.0   4000000.0  10.0  378.0  2.0  52500.0  35000.0  31500.0   
..        ...         ...   ...    ...  ...      ...      ...      ...   
66   630000.0  24000000.0  30.0  378.0  4.0  52500.0  35000.0  31500.0   
67   630000.0  24000000.0  40.0  252.0  2.0  52500.0  35000.0  31500.0   
68   990000.0  24000000.0  40.0  396.0  2.0  82500.0  55000.0  49500.0   
69   630000.0  24000000.0  50.0  315.0  2.0  52500.0  35000.0  31500.0   
70   630000.0  24000000.0  60.0  378.0  2.0  52500.0  35000.0  31500.0   

         F7       F6       F5       F4       F3      F2      F1  
0   22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  
1   33000.0  22500.0  22000.0  15000.0  10000.0  9000.0  6000.0  
2   39000.0  26000.0  22500.0  15000.0  10000.0  9000.0  6000.0  
3   22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  
4   22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  
..      ...      ...      ...      ...      ...     ...     ...  
66  22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  
67  22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  
68  33000.0  22500.0  22000.0  15000.0  10000.0  9000.0  6000.0  
69  22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  
70  22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  

[71 rows x 15 columns]

In [48]:
df.to_csv("Results.csv", index=None)

In [49]:
pd.read_csv("Results.csv")

X           I     M      N    P      F10       F9       F8  \
0    630000.0   4000000.0   5.0  189.0  2.0  52500.0  35000.0  31500.0   
1    990000.0   4000000.0   5.0  297.0  2.0  82500.0  55000.0  49500.0   
2   1170000.0   4000000.0   5.0  351.0  2.0  97500.0  65000.0  58500.0   
3    630000.0   4000000.0   5.0  378.0  4.0  52500.0  35000.0  31500.0   
4    630000.0   4000000.0  10.0  378.0  2.0  52500.0  35000.0  31500.0   
..        ...         ...   ...    ...  ...      ...      ...      ...   
66   630000.0  24000000.0  30.0  378.0  4.0  52500.0  35000.0  31500.0   
67   630000.0  24000000.0  40.0  252.0  2.0  52500.0  35000.0  31500.0   
68   990000.0  24000000.0  40.0  396.0  2.0  82500.0  55000.0  49500.0   
69   630000.0  24000000.0  50.0  315.0  2.0  52500.0  35000.0  31500.0   
70   630000.0  24000000.0  60.0  378.0  2.0  52500.0  35000.0  31500.0   

         F7       F6       F5       F4       F3      F2      F1  
0   22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  
1   33000.0  22500.0  22000.0  15000.0  10000.0  9000.0  6000.0  
2   39000.0  26000.0  22500.0  15000.0  10000.0  9000.0  6000.0  
3   22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  
4   22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  
..      ...      ...      ...      ...      ...     ...     ...  
66  22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  
67  22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  
68  33000.0  22500.0  22000.0  15000.0  10000.0  9000.0  6000.0  
69  22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  
70  22500.0  21000.0  15000.0  14000.0  10000.0  9000.0  6000.0  

[71 rows x 15 columns]